name: Build images and deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: environment

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/awesome-bulletins:latest

  deploy:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Print selected environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./docker-compose.yml"
          target: "./app"

      - name: Prepare environment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            uname -a
            echo "Stopping containers for update"
            docker compose down
            echo "Logging in to github container registry"
            echodocker login ghcr.io/${{ github.repository }} -u ${{ secrets.SSH_USERNAME }} -p {{ secrets.DEPLOY_USER_REGISTRY_PASSWORD }}
            echo "Pulling new images"
            docker compose pull
            echo "Starting up containers"
            docker compose up -d
            echo "Logging out from registry"
